substitutions:
  # Device
  device_name: temp_sensor_master_bedroom
  timezone: America/New_York
  logger_level: DEBUG
  logger_baud_rate: "115200"
  # Board
  platform: ESP8266
  board: esp12e
  # Pinout
  dht22_pin: GPIO13
  led_red_pin: GPIO12
  led_green_pin: GPIO14
  led_blue_pin: GPIO4
  # Firware
  firmware_version: "esp-dht22-rel0.0"

<<: !include collection/esp-dht22.yaml